// ─── Excel Service — Monthly Payroll Export ─────────────────────────────────
import ExcelJS from 'exceljs';

function formatINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);
}

const MONTHS = ['','January','February','March','April','May','June','July','August','September','October','November','December'];

export interface PayrollExcelInput {
  companyName: string;
  month: number;
  year: number;
  payslips: Array<{
    employeeName: string;
    employeeRole: string;
    breakdown: {
      basicSalary: number; hra: number; overtimePay: number; festivalBonus: number;
      grossPay: number; unpaidLeaveDeduction: number; pfDeduction: number;
      esiDeduction: number; netPay: number; warnings: string[];
    };
    netPay: number;
  }>;
  totalPayout: number;
}

export async function generatePayrollExcel(input: PayrollExcelInput): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'PayLite';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Payroll Summary');

  // Title
  sheet.mergeCells('A1:K1');
  const titleCell = sheet.getCell('A1');
  titleCell.value = `${input.companyName} — Payroll Summary: ${MONTHS[input.month]} ${input.year}`;
  titleCell.font = { size: 14, bold: true, color: { argb: 'FF185FA5' } };
  titleCell.alignment = { horizontal: 'center' };

  // Headers (row 3)
  const headers = ['#', 'Employee', 'Role', 'Basic', 'HRA', 'OT Pay', 'Bonus', 'Gross', 'PF', 'ESI', 'Unpaid Ded.', 'Net Pay'];
  const headerRow = sheet.addRow([]);
  sheet.addRow(headers);
  const hRow = sheet.getRow(3);
  hRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  hRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF185FA5' } };
  hRow.alignment = { horizontal: 'center' };

  // Column widths
  sheet.getColumn(1).width = 4;
  sheet.getColumn(2).width = 22;
  sheet.getColumn(3).width = 16;
  for (let i = 4; i <= 12; i++) sheet.getColumn(i).width = 14;

  // Data rows
  input.payslips.forEach((ps, idx) => {
    const b = ps.breakdown;
    const row = sheet.addRow([
      idx + 1, ps.employeeName, ps.employeeRole,
      b.basicSalary, b.hra, b.overtimePay, b.festivalBonus,
      b.grossPay, b.pfDeduction, b.esiDeduction, b.unpaidLeaveDeduction, b.netPay,
    ]);

    // Format currency columns
    for (let c = 4; c <= 12; c++) {
      const cell = row.getCell(c);
      cell.numFmt = '#,##0.00';
    }

    // Alternate row colors
    if (idx % 2 === 0) {
      row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F8FC' } };
    }
  });

  // Summary row
  const summaryRow = sheet.addRow([]);
  const totalRow = sheet.addRow([
    '', '', 'TOTAL', '', '', '', '', '', '', '', '',
    input.totalPayout,
  ]);
  totalRow.font = { bold: true, size: 12 };
  totalRow.getCell(12).numFmt = '#,##0.00';
  totalRow.getCell(12).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF185FA5' } };
  totalRow.getCell(12).font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };

  // Add borders to data area
  const lastDataRow = sheet.lastRow?.number || 4;
  for (let r = 3; r <= lastDataRow; r++) {
    for (let c = 1; c <= 12; c++) {
      const cell = sheet.getRow(r).getCell(c);
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFD0D0D0' } },
        bottom: { style: 'thin', color: { argb: 'FFD0D0D0' } },
        left: { style: 'thin', color: { argb: 'FFD0D0D0' } },
        right: { style: 'thin', color: { argb: 'FFD0D0D0' } },
      };
    }
  }

  // Footer
  const footerRow = sheet.addRow([]);
  const genRow = sheet.addRow(['Generated by PayLite']);
  genRow.font = { italic: true, color: { argb: 'FF999999' }, size: 9 };

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
