// ─── PDF Service — Payslip Generation with pdfmake ──────────────────────────
import PdfPrinter from 'pdfmake';
import { TDocumentDefinitions } from 'pdfmake/interfaces';

function formatINR(amount: number): string {
  return '₹' + new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);
}

const MONTHS = ['','January','February','March','April','May','June','July','August','September','October','November','December'];

export interface PayslipPDFInput {
  companyName: string;
  employeeName: string;
  employeeRole: string;
  month: number;
  year: number;
  breakdown: {
    basicSalary: number; hra: number; overtimePay: number; festivalBonus: number;
    grossPay: number; unpaidLeaveDeduction: number; pfDeduction: number;
    esiDeduction: number; netPay: number; warnings: string[];
  };
  netPay: number;
}

export async function generatePayslipPDF(input: PayslipPDFInput): Promise<Buffer> {
  const printer = new PdfPrinter({
    Helvetica: { normal: 'Helvetica', bold: 'Helvetica-Bold', italics: 'Helvetica-Oblique', bolditalics: 'Helvetica-BoldOblique' },
  });

  const totalDed = input.breakdown.pfDeduction + input.breakdown.esiDeduction + input.breakdown.unpaidLeaveDeduction;
  const m = [0,0,0,0] as [number,number,number,number];
  const mb5 = [0,0,0,5] as [number,number,number,number];
  const mb15 = [0,0,0,15] as [number,number,number,number];
  const mb20 = [0,0,0,20] as [number,number,number,number];
  const r = 'right' as const;
  const c = 'center' as const;

  const docDef: TDocumentDefinitions = {
    defaultStyle: { font: 'Helvetica' }, pageSize: 'A4', pageMargins: [40,40,40,60],
    content: [
      { columns: [{ text: input.companyName.toUpperCase(), style: 'companyName', width: '*' }, { text: 'PAYSLIP', style: 'payslipTitle', width: 'auto', alignment: r }], margin: mb5 },
      { canvas: [{ type: 'line', x1:0, y1:0, x2:515, y2:0, lineWidth:2, lineColor:'#185FA5' }], margin: mb15 },
      { columns: [{ width:'*', text: [{ text:'Employee: ', bold:true }, input.employeeName] }, { width:'*', text: [{ text:'Designation: ', bold:true }, input.employeeRole] }], margin: mb5 },
      { columns: [{ width:'*', text: [{ text:'Pay Period: ', bold:true }, `${MONTHS[input.month]} ${input.year}`] }, { width:'*', text: [{ text:'Generated: ', bold:true }, new Date().toLocaleDateString('en-IN')] }], margin: mb20 },
      { columns: [
        { width:'50%', table: { headerRows:1, widths:['*','auto'], body: [
          [{ text:'EARNINGS', style:'tableHeader', colSpan:2, alignment:c },{}],
          ['Basic Salary',{ text:formatINR(input.breakdown.basicSalary), alignment:r }],
          ['HRA',{ text:formatINR(input.breakdown.hra), alignment:r }],
          ['Overtime Pay',{ text:formatINR(input.breakdown.overtimePay), alignment:r }],
          ['Festival Bonus',{ text:formatINR(input.breakdown.festivalBonus), alignment:r }],
          [{ text:'Gross Pay', bold:true },{ text:formatINR(input.breakdown.grossPay), alignment:r, bold:true }],
        ]}, layout:{ fillColor:(i: number)=> i===0?'#185FA5':i%2===0?'#F5F8FC':null }, margin:[0,0,10,0] as [number,number,number,number] },
        { width:'50%', table: { headerRows:1, widths:['*','auto'], body: [
          [{ text:'DEDUCTIONS', style:'tableHeader', colSpan:2, alignment:c },{}],
          ['Provident Fund',{ text:formatINR(input.breakdown.pfDeduction), alignment:r }],
          ['ESI',{ text:formatINR(input.breakdown.esiDeduction), alignment:r }],
          ['Unpaid Leave Ded.',{ text:formatINR(input.breakdown.unpaidLeaveDeduction), alignment:r }],
          ['',''],
          [{ text:'Total Deductions', bold:true },{ text:formatINR(totalDed), alignment:r, bold:true }],
        ]}, layout:{ fillColor:(i: number)=> i===0?'#D32F2F':i%2===0?'#FFF5F5':null }, margin:[10,0,0,0] as [number,number,number,number] },
      ], margin: mb20 },
      { table: { widths:['*'], body:[[{ text:[{ text:'NET PAY: ', fontSize:16, bold:true },{ text:formatINR(input.netPay), fontSize:20, bold:true, color:'#185FA5' }], alignment:c, margin:[0,15,0,15] as [number,number,number,number] }]]},
        layout:{ fillColor:()=>'#F0F7FF', hLineColor:()=>'#185FA5', vLineColor:()=>'#185FA5', hLineWidth:()=>2, vLineWidth:()=>2 }, margin:mb20 },
    ],
    footer: { columns:[{ text:'Generated by PayLite', alignment:c, fontSize:8, color:'#999', margin:[0,20,0,0] as [number,number,number,number] }]},
    styles: { companyName:{ fontSize:18, bold:true, color:'#185FA5' }, payslipTitle:{ fontSize:14, bold:true, color:'#666' }, tableHeader:{ bold:true, fontSize:11, color:'white' }},
  };

  return new Promise<Buffer>((resolve, reject) => {
    const doc = printer.createPdfKitDocument(docDef);
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}
